# Generated by Django 2.0 on 2018-09-07 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 11, 30, 9, 125806), verbose_name='date created'),
        ),
    ]
