# Generated by Django 2.0 on 2018-09-07 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180907_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreviews',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 14, 16, 21, 985803), verbose_name='date created'),
        ),
        migrations.DeleteModel(
            name='CompanyReviews',
        ),
    ]
