# Generated by Django 2.0 on 2018-09-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180908_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
    ]
