# Generated by Django 2.0 on 2018-09-07 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20180907_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 16, 56, 37, 972603), verbose_name='date created'),
        ),
    ]
