# Generated by Django 2.0 on 2018-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyByType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=35)),
                ('company_twitter', models.CharField(blank=True, max_length=50)),
                ('company_facebook', models.CharField(blank=True, max_length=50)),
                ('company_instagram', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('comp_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('comp_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('company_type', models.CharField(choices=[('FOOD & DRINKS', 'Food & Drinks'), ('ENTERTAINMENT', 'Entertainment'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('RELIGIOUS SERVICES', 'Religious Services'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
            ],
        ),
    ]
