# Generated by Django 2.0 on 2018-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontacts',
            name='comapany_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
