# Generated by Django 2.0 on 2018-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybytype',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
