# Generated by Django 2.0 on 2018-09-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontacts',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companylocation',
            name='company_name',
        ),
        migrations.DeleteModel(
            name='CompanyContacts',
        ),
        migrations.DeleteModel(
            name='CompanyLocation',
        ),
    ]
