# Generated by Django 2.0 on 2018-09-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180906_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontacts',
            name='comapany_phone',
        ),
    ]
