# Generated by Django 2.0 on 2018-09-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companycontacts_comapany_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybytype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='companycontacts',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='companylocation',
            name='slug',
        ),
    ]
